### ISSUE TITLE
Diagram Generation Crashes with `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#13]
https://github.com/Reithger/Project-Diagram-Generator/blob/2f4fc02622c939bd22054ce9603a66eca1ae7653/src/analysis/process/file/JavaFile.java#L118
```
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 4
        at analysis.process.file.JavaFile.processFunction(JavaFile.java:118)
        at analysis.process.file.JavaFile.extractFunctions(JavaFile.java:220)
        at analysis.process.file.GenericFile.processClass(GenericFile.java:115)
        at analysis.process.file.GenericFile.process(GenericFile.java:98)
        at analysis.process.Explore.run(Explore.java:54)
        at image.ConvertVisual.generateUMLDiagram(ConvertVisual.java:32)
        at ui.Display$1.clickEvent(Display.java:136)
        at input.NestedEventReceiver.clickEvent(NestedEventReceiver.java:103)
        at visual.panel.ElementPanel.clickEvent(ElementPanel.java:453)
        at input.manager.actionevent.MouseActionEvent.execute(MouseActionEvent.java:49)
        at input.manager.TimedThread.run(TimedThread.java:58)
Fail forward exception: ActionEventManager's TimedThread object produced an exception while executing input.
```
Related to https://github.com/Reithger/Project-Diagram-Generator/issues/11#issuecomment-1312199281

**Comment by Reithger** [comment]
Should be fixed by most recent update, gotta watch out for when you mess with regex.
