### ISSUE TITLE
Diagram Generation Crashes with `NullPointerException`

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#8]
## Crash Info

https://github.com/Reithger/Project-Diagram-Generator/blob/ab6c0d6fa80c4ab0d9a2554ccaa4ba732497d997/src/analysis/process/file/GenericFile.java#L96
```
java.lang.NullPointerException: Cannot invoke "analysis.process.Cluster.getComponents()" because the return value of "analysis.process.Cluster.getCluster(String[])" is null
        at analysis.process.file.GenericFile.process(GenericFile.java:96)
        at analysis.process.Explore.run(Explore.java:54)
        at image.ConvertVisual.generateUMLDiagram(ConvertVisual.java:32)
        at ui.Display$1.clickEvent(Display.java:136)
        at input.NestedEventReceiver.clickEvent(NestedEventReceiver.java:103)
        at visual.panel.ElementPanel.clickEvent(ElementPanel.java:453)
        at visual.panel.ElementPanel.clickReleaseEvent(ElementPanel.java:460)
        at input.manager.actionevent.MouseActionEvent.execute(MouseActionEvent.java:46)
        at input.manager.TimedThread.run(TimedThread.java:58)
Fail forward exception: ActionEventManager's TimedThread object produced an exception while executing input.
```

## Environments Tested

- Ubuntu 20.04 LTS, OpenJDK 11.0.16.1 LTS (Microsoft Build)
- Ubuntu 20.04 LTS, OpenJDK 17.0.4.1 LTS (Microsoft Build)
- Windows 11 21H2 (build 22000.613), OpenJDK 11.0.16.1 LTS (Microsoft Build)

**Comment by Reithger** [comment]
Should be resolved now with recent changes to interpretation of class header definitions (the "public abstract final ClassName" stuff)
